SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS JCQ_CODE;
DROP TABLE IF EXISTS JCQ_ITEMSCALES;
DROP TABLE IF EXISTS JCQ_ITEM;
DROP TABLE IF EXISTS JCQ_QUESTIONSCALES;
DROP TABLE IF EXISTS JCQ_QUESTION;
DROP TABLE IF EXISTS JCQ_PAGE;
DROP TABLE IF EXISTS JCQ_PROJECT;
DROP TABLE IF EXISTS JCQ_SCALE;




/* Create Tables */

CREATE TABLE JCQ_CODE
(
	ID INT NOT NULL AUTO_INCREMENT,
	SCALEID INT NOT NULL,
	ORD INT NOT NULL,
	CODE INT NOT NULL,
	LABEL TEXT,
	PRIMARY KEY (ID)
);


CREATE TABLE JCQ_ITEM
(
	ID INT NOT NULL AUTO_INCREMENT,
	QUESTIONID INT NOT NULL,
	ORD INT NOT NULL,
	VARNAME VARCHAR(255) NOT NULL,
	MANDATORY INT(1) DEFAULT 1 NOT NULL,
	TEXTLEFT TEXT,
	TEXTRIGHT TEXT,
	PRIMARY KEY (ID)
);


CREATE TABLE JCQ_ITEMSCALES
(
	ITEMID INT NOT NULL,
	SCALEID INT NOT NULL,
	VARNAME VARCHAR(0)
);


CREATE TABLE JCQ_PAGE
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PROJECTID INT NOT NULL,
	ORD INT NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE JCQ_PROJECT
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	CLASSFILE VARCHAR(255) NOT NULL,
	CLASSNAME VARCHAR(255) NOT NULL,
	DESCRIPTION TEXT,
	ANONYMOUSANSWERS INT(1) DEFAULT 0 NOT NULL,
	MULTIPLEANSWERS INT(1) DEFAULT 0 NOT NULL,
	PRIMARY KEY (ID)
);


CREATE TABLE JCQ_QUESTION
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PAGEID INT NOT NULL,
	ORD INT NOT NULL,
	TYPE INT NOT NULL,
	DATATYPE ENUM('INT','REAL','TEXT') NOT NULL,
	VARNAME VARCHAR(255),
	MANDATORY INT(1) DEFAULT 1,
	TEXT TEXT,
	ADVISE TEXT,
	PREPOST TEXT,
	WIDTH_SCALE INT,
	ALTERNATE_BG INT(1),
	PRIMARY KEY (ID)
);


CREATE TABLE JCQ_QUESTIONSCALES
(
	QUESTIONID INT NOT NULL,
	SCALEID INT NOT NULL,
	VARNAME VARCHAR(255)
);


CREATE TABLE JCQ_SCALE
(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(255) NOT NULL,
	PREPOST TEXT,
	PRIMARY KEY (ID)
);



/* Create Foreign Keys */

ALTER TABLE JCQ_ITEMSCALES
	ADD FOREIGN KEY (ITEMID)
	REFERENCES JCQ_ITEM (ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE JCQ_QUESTION
	ADD FOREIGN KEY (PAGEID)
	REFERENCES JCQ_PAGE (ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE JCQ_PAGE
	ADD FOREIGN KEY (PROJECTID)
	REFERENCES JCQ_PROJECT (ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE JCQ_ITEM
	ADD FOREIGN KEY (QUESTIONID)
	REFERENCES JCQ_QUESTION (ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE JCQ_QUESTIONSCALES
	ADD FOREIGN KEY (QUESTIONID)
	REFERENCES JCQ_QUESTION (ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE JCQ_CODE
	ADD FOREIGN KEY (SCALEID)
	REFERENCES JCQ_SCALE (ID)
	ON UPDATE CASCADE
	ON DELETE CASCADE
;


ALTER TABLE JCQ_ITEMSCALES
	ADD FOREIGN KEY (SCALEID)
	REFERENCES JCQ_SCALE (ID)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
;


ALTER TABLE JCQ_QUESTIONSCALES
	ADD FOREIGN KEY (SCALEID)
	REFERENCES JCQ_SCALE (ID)
	ON UPDATE CASCADE
	ON DELETE RESTRICT
;



